-- 코드를 입력하세요
SELECT distinct(H.CAR_ID)
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H, CAR_RENTAL_COMPANY_CAR C
WHERE H.CAR_ID = C.CAR_ID
    AND CAR_TYPE = "세단"
    AND date_format(START_DATE,"%Y-%m") = "2022-10"
ORDER BY H.CAR_ID desc